### ISSUE TITLE
Sonar Execution success but logs - "The sonar-runner did not complete successfully"

### ISSUE THREAD

**Issue by richardjharding** [Microsoft/vso-agent-tasks#963] opened 2015-12-10 12:20 UTC
I'm using VSTS (aka VSO) with a build server hosted ona vm in azure and a sonarqube installation also hosted on a vm in azure

Its a new installation of SonarQube 5.2 , with the 2.4 runnter all on windows

I've used the new agent tasks to perform an analysis on a .net solution

the analysis completes and the results are sent to sonarqube and processed correctly 

But in the build log he following is reported

<pre>
12:07:22.255 INFO  - Analysis reports compressed in 3540ms, zip size=10 MB
12:07:27.306 INFO  - Analysis reports sent to server in 5050ms
12:07:27.308 INFO  - ANALYSIS SUCCESSFUL, you can browse http://MysonarServer:9000/dashboard/index/ELD
12:07:27.308 INFO  - Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report.
12:07:27.308 INFO  - More about the report processing at http://MySonarServer9000/api/ce/task?id=AVGLyef2h5t5zqj7pDHg
12:07:27.309 INFO  - Executing post-job org.sonar.plugins.jmeter.JMeterPostJob
12:07:27.310 INFO  - No JTL files found in /target/jmeter/results
12:07:27.310 INFO  - No JTL files found in /target/jmeter-reports
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
Total time: 12:02.571s
Final Memory: 15M/2252M
INFO: ------------------------------------------------------------------------

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0

The sonar-runner did not complete successfully
12:07:30.674  Creating a summary markdown file...

Post-processing failed. Exit code: 1

Unexpected exit code received from batch file: 1

******************************************************************************

Finishing task: SonarQubePostTest

******************************************************************************

</pre>

As a result the build is marked as a partial success

How can I debug whats causing a success from sonar runner to be handled as a failure by the task and fix it?

Many thanks

**Comment by bryanmacfarlane** [comment] 2015-12-10 13:07
Bogdan worked on SonarQube int

**Comment by bgavrilMS** [comment] 2015-12-10 13:08
Hi @richardjharding 

Can you enable more verbose logging to try to understand what exactly is failing please? To do this: 

a. Enable TFS Build debug logging by adding a variable named system.debug and setting its value to 'true'
b. Enable the SonarQube components verbose logging - In your SonarQube Begin task, under Advanced > Additional Settings, please add:

/d:sonar.verbose=true

**Comment by richardjharding** [comment] 2015-12-10 15:59
thanks for the quick response here is what I have after enabling the logging as you suggest

<pre>
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
Total time: 2:39.175s
Final Memory: 26M/1374M
INFO: ------------------------------------------------------------------------

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
Process returned exit code 0

The sonar-runner did not complete successfully
15:56:58.838  Creating a summary markdown file...

Post-processing failed. Exit code: 1

System.Exception: Unexpected exit code received from batch file: 1

at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeBatchScriptCmdlet.ProcessRecord()

at System.Management.Automation.CommandProcessor.ProcessRecord()

******************************************************************************

Finishing task: SonarQubePostTest

******************************************************************************
</pre>

**Comment by bgavrilMS** [comment] 2015-12-10 17:08
Also adding @duncanpMS

**Comment by bgavrilMS** [comment] 2015-12-11 08:29
@richardjharding  - It seems that the sonar-scanner is failing silently for some reason. This component is developed by SonarSource so can I ask you to post this question to StackOverflow and tag it "SonarQube" - SonarSource engineers will also be able to have a look. Also - please include the SonarQube server version and the C# plugin version details. Many thanks!

**Comment by duncanpMS** [comment] 2015-12-15 09:50
@richardjharding Do any other warnings/errors appear in the sonar-runner part of the log (other than the warning about *MaxPermSize*)? Also, can you try changing your configuration to remove the setting for *MaxPermSize* to see if that makes any difference? Thanks.

**Comment by duncanpMS** [comment] 2015-12-15 14:14
@richardjharding, @bgavrilMS FYI I've created [SONARMSBRU-202](https://jira.sonarsource.com/browse/SONARMSBRU-202) to track this issue.

**Comment by richardjharding** [comment] 2015-12-15 14:46
ok it does look like that warning was making it look like a failure - I removed the MaxPermSize (in my case was in a SONAR_OPTS env var) this results  in clean log and no error reported by the task

<pre>
Post-processing succeeded.
******************************************************************************
Finishing task: SonarQubePostTest
******************************************************************************
******************************************************************************
Finishing Build
******************************************************************************
Worker Worker-cd4bb22a-a9c9-428f-b2d3-101406463b61 finished running job cd4bb22a-a9c9-428f-b2d3-101406463b61
</pre>

**Comment by duncanpMS** [comment] 2015-12-15 14:51
Thanks, @richardjharding, useful to know. Looks like we might need to change the *MSBuild SonarQube Scanner* so that it just looks at the code returned from the *sonar-runner* and not the content written to the error stream.

**Comment by bgavrilMS** [comment] 2016-01-25 10:29
Closing this as we are tracking the issue on Jira.

**Closed by bgavrilMS** 2016-01-25 10:29 UTC

**Comment by yadullahi** [comment] 2020-02-20 15:35
I have been trying to execute the sonar qube scanner through Command line. Can anyone help me out

15:32:00.094 ERROR: Error during SonarQube Scanner execution
org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarQube
        at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:85)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:74)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:70)
        at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:185)
        at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:73)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Fail to get bootstrap index from server
        at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex(BootstrapIndexDownloader.java:42)
        at org.sonarsource.scanner.api.internal.JarDownloader.getScannerEngineFiles(JarDownloader.java:58)
        at org.sonarsource.scanner.api.internal.JarDownloader.download(JarDownloader.java:53)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:76)
        ... 7 more
Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9000
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.RealConnection.connect(RealConnection.java:183)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.RealCall.execute(RealCall.java:81)
        at org.sonarsource.scanner.api.internal.ServerConnection.callUrl(ServerConnection.java:113)
        at org.sonarsource.scanner.api.internal.ServerConnection.downloadString(ServerConnection.java:98)
        at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex(BootstrapIndexDownloader.java:39)
        ... 10 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.platform.Platform.connectSocket(Platform.java:130)
        at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
        ... 31 more
15:32:00.096 ERROR:
15:32:00.096 ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.

**Comment by duncanp-sonar** [comment] 2020-02-21 17:14
@yadullahi please ask your question in the SonarSource community forum: https://community.sonarsource.com/c/help/sq/10

**Comment by Maddalarajesh** [comment] 2023-08-14 07:56
at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: org.sonarqube.ws.client.HttpException: Error 500 on https://sonarqube.develop.yp-uae.waveaxis.space/api/ce/submit?projectKey=12345&projectName=wd&characteristic=pullRequest%3D4798 : {"errors":[{"msg":"An error has occurred. Please contact your administrator"}]}
	at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
	at org.sonar.scanner.bootstrap.DefaultScannerWsClient.failIfUnauthorized(DefaultScannerWsClient.java:128)
	at org.sonar.scanner.bootstrap.DefaultScannerWsClient.call(DefaultScannerWsClient.java:89)
	at org.sonar.scanner.report.ReportPublisher.upload(ReportPublisher.java:225)
	... 21 more
ERROR: 
##[error]The SonarScanner did not complete successfully
The SonarScanner did not complete successfully
##[error]07:34:52.771  Post-processing failed. Exit code: 1
07:34:52.771  Post-processing failed. Exit code: 1
##[error]The process '/usr/bin/dotnet' failed with exit code 1
