### ISSUE TITLE
xPlat: Gradle step succeeds even though the tests fail

### ISSUE THREAD

**Issue by RoopeshNair** [Microsoft/vso-agent-tasks#961] opened 2015-12-10 08:25 UTC
Gradle step on xPlat agent succeeds even though the tests fail. 

Previously it used to fail the task now Build/Release succeeds though the task has failures.

----------step log-----------
2015-12-10T06:14:19.408Z: 57 tests completed, 4 failed 
2015-12-10T06:14:20.920Z: * What went wrong: 
2015-12-10T06:14:20.920Z: Execution failed for task ':test'. 
2015-12-10T06:14:20.921Z: There were failing tests. See the report at: file:///home/myadmin/xngine/_work/release/efa77816bb57b99ce22d9f10044bf69b35c741c31c14a0af1eb7742cf4c4ee94/PartsUnlimitedMRP.CI/drop/Backend/OrderService/build/reports/tests/index.htm2015-12-10T06:14:20.922Z: * Try: 
2015-12-10T06:14:20.927Z:  option to get more log output. 
2015-12-10T06:14:20.928Z: * Exception is: 
2015-12-10T06:14:20.930Z: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'. 
2015-12-10T06:14:20.930Z: 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)

**Comment by yacaovsnc** [comment] 2015-12-15 21:55
Hi @RoopeshNair, I can't reproduce this failure:
******************************************************************************
Running Gradle
******************************************************************************
/Users/yacao/Repos/vso-agent/_package/vsoxplat/_work/6/s/bugbash/Gradle/gradlew build
UP-TO-DATE
UP-TO-DATE
FAILED
    org.junit.ComparisonFailure at AppTest.java:17
1 test completed, 1 failed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/yacao/Repos/vso-agent/_package/vsoxplat/_work/6/s/bugbash/Gradle/build/reports/tests/index.html
* Try:
--debug option to get more log output.
BUILD FAILED
Total time: 3.025 secs
/Users/yacao/Repos/vso-agent/_package/vsoxplat/_work/6/s/bugbash/Gradle/gradlew failed with return code: 1
 
Start: Results.Publish async Command
End: Results.Publish async Command
----------------------------------------------------------
It seems your xplat agent maybe old (https://github.com/Microsoft/vso-agent) given the long hash in your path.  Can you update to the latest release and try again?

**Comment by yacaovsnc** [comment] 2016-01-07 15:30
Closing this issue because I can't reproduce this with latest code.  Please feel free to reopen if the problem is still outstanding.  I will take a look again then.  

Thanks.

**Closed by yacaovsnc** 2016-01-07 15:30 UTC
