### ISSUE TITLE
No file format header found (Build Step/Nuget restore)

### ISSUE THREAD

**Issue by omarpando** [Microsoft/vso-agent-tasks#571] opened 2015-09-22 13:04 UTC
Hello, I followed the article:
https://msdn.microsoft.com/Library/vs/alm/Build/azure/deploy-aspnet5

I am getting "No file format header found."

```
Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\tasks\VSBuild\1.0.15\VSBuild.ps1
2015-09-22T09:51:03.4563485Z C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agent\worker\tools\NuGet.exe restore "C:\a\ce1f12e0\Trucko Demo\src\TruckoDemo\TruckoDemo.xproj" -NonInteractive
2015-09-22T09:51:04.4097630Z ##[error]No file format header found.
```

**Comment by FrederickJSmall** [comment] 2015-09-22 23:41
Having the same issue. It looks to be related to Nuget more than VSO. if you run the command line locally against a xproj you get the same error. If anyone has a solution please advise

**Comment by kowsheek** [comment] 2015-09-23 16:51
I got the same:

`No file format header found.
Unexpected exit code 1 returned from tool NuGet.exe`

**Comment by chrisrpatterson** [comment] 2015-09-23 17:15
You can't run nuget restore against anything other than an SLN file.

**Comment by chrisrpatterson** [comment] 2015-09-23 17:16
@omarpando you should uncheck restore nuget packages on that vsbuild task.

**Comment by kowsheek** [comment] 2015-09-23 18:19
@chrisrpatterson's solution worked for me

**Comment by bryanmacfarlane** [comment] 2015-09-23 19:12
Chris, should we add some validation/advisement to the task?

**Comment by omarpando** [comment] 2015-09-24 00:37
Getting now  *System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.*


global.json
```
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-beta7",
    "runtime": "clr"
  }
}
```

Restore NuGet Packages uncheked
![build](https://cloud.githubusercontent.com/assets/1749353/10062653/e1a1b7ee-6232-11e5-88cf-59935ca1ff8b.JPG)


```
2015-09-24T00:17:20.3383841Z          C:\Users\buildguest\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\dnx.exe --appbase "C:\a\96aede60\NewApp\src\NewApp" "C:\Users\buildguest\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\lib\Microsoft.DNX.PackageManager\Microsoft.DNX.PackageManager.dll" pack "C:\a\96aede60\NewApp\src\NewApp" --configuration debug --out "..\..\artifacts\bin\NewApp"
2015-09-24T00:17:21.2932077Z          System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DNX.PackageManager' or one of its dependencies. The system cannot find the file specified.
2015-09-24T00:17:21.2952067Z          File name: 'Microsoft.DNX.PackageManager'
2015-09-24T00:17:21.2962076Z             at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
```

**Comment by chrisrpatterson** [comment] 2015-09-24 00:43
Did you restore you dnx packages? Msbuild I'd not going to do that for you and because dnx is in such early beta there is no oob support for it in the version of NuGet installed with the build agent.

Sent from my Windows Phone
________________________________

**Comment by DarcSlate** [comment] 2015-09-24 03:02
Yeah had the same issue. Had to step back to beta5. With the and unchecking restore nuget packages  I was able to get a build going. Now debugging the Publish build artifacts

**Comment by Rafael-Miceli** [comment] 2015-10-06 13:09
I'm having the same problem with a .csproj file.

Is there a way with VSO to restore the packages and build the .csproj without build the entire solution?

**Comment by jp7253** [comment] 2015-10-08 14:25
I too followed the same article to get a VSO build set up for a DNX Beta7 project, and I'm now getting the same System.IO.FileNotFoundException for Microsoft.DNX.PackageManager. @chrisrpatterson the Prebuild.ps1 task does the dnu restore for any project.json files in the solution so this should already have been done before msbuild is called. @DarcSlate any idea why moving back to Beta5 worked for you? I had this all working for Beta6 and only recently started getting this issue.

**Comment by jp7253** [comment] 2015-10-08 15:54
Having done some more research I believe the issue is caused by the fact that the Hosted build agent in VSO does not have the latest "ASP.NET and Web Tools" version installed https://github.com/aspnet/dnx/issues/2426 @omarpando did you ever find a solution?

**Comment by praneetloke** [comment] 2015-10-21 00:08
I just hit this error preventing me from moving to the new build definitions.

**Comment by phanibitla** [comment] 2015-10-21 09:38
I got the same error and it got resolved by unchecking the options "Restore NuGet Packages” and “Clean” in MS Build step of the definition.

![scrn](https://cloud.githubusercontent.com/assets/15228866/10633021/9044d1a4-7805-11e5-930c-9b6b4bd71a0c.jpg)

**Comment by praneetloke** [comment] 2015-10-21 23:28
@phanibitla you beat me to it. I did exactly that. Is there a reason to ever have that checked for a .ccproj?

**Comment by chrisrpatterson** [comment] 2015-10-22 01:01
No, Nuget restore only works for solutions.

**Comment by orhanmaden** [comment] 2015-11-13 13:05
NuGet restore also works with packages.config files. This command restores the packages defined in the config file to the specified output directory.

`nuget.exe restore .\pathto\packages.config -packagesdirectory .\pathto\outputdir

**Comment by dac-scherevko** [comment] 2015-12-04 21:30
To confirm, if I am building a <strong>cloud service</strong> in VSTS (using Visual Studio Online and hosted build agents):
- I need to uncheck Restore NuGet Packages option in the Build Definition?
- and I have to have all nuget packages in packages folder checked in, to have the referenced dll files available for the build agents?

Thanks,
Serge

**Comment by chrisrpatterson** [comment] 2015-12-04 21:48
NuGet restore only works against a solution file.  I would recommend you run the NuGet task on your solution file and then build your cloud service package targeting your .ccproj file.  The Cloud Service Deployment template is a great place to start as it sets everything up for you.

**Comment by praneetloke** [comment] 2015-12-04 23:41
@dac-scherevko as @chrisrpatterson mentioned, have the Nuget resotre enabled for the .sln build step but unchecked for the .ccproj build step.

**Comment by dac-scherevko** [comment] 2015-12-08 21:22
Thanks  @chrisrpatterson and @praneetloke! That helped.

However, there is one thing I cannot explain: if I create a new cloud service solution with a worker role (in VS2015), then everything is fine; but if I try to build an old cloud service solution in VSO, then for some reason, the build agent tries restoring Nuget packages and errors: 
".2>RestorePackages:
         "..\.nuget\NuGet.exe" install "C:\a\1\s\WorkerRole\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "..\ "
.nuget\NuGet.targets(100,9): Error : The path is not of a legal form.
     2>C:\a\1\s\.nuget\NuGet.targets(100,9): error : The path is not of a legal form. [C:\a\1\s\WorkerRole\WorkerRole.csproj]
.nuget\NuGet.targets(100,9): Error MSB3073: The command ""..\.nuget\NuGet.exe" install "C:\a\1\s\WorkerRole\packages.config" -source "" -NonInteractive -RequireConsent -solutionDir "..\ "" exited with code 1."

Of course, I have the Restore NuGet Packages option unchecked in the build definition.
Do you have any ideas why that can happen?

Thanks,
Serge

**Comment by chrisrpatterson** [comment] 2015-12-08 22:32
It looks like you are trying to run the old nugget.targets based method which has problems.  Try and remove that targets file from your solution and projects and see if that solves the issue.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by dac-scherevko** [comment] 2015-12-10 16:59
@chrisrpatterson - thanks! That helped as well. 
For more details I followed this: https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore
- removed nuget.targets and nuget.exe files from .nuget folder in my solution 
- and changed all my csproj files
and, yes, it works fine now.

Thanks again!

**Comment by vtbassmatt** [comment] 2016-01-06 16:10
@omarpando and @dac-scherevko - looks like you've got resolution. OK for me to close this issue?

**Comment by dac-scherevko** [comment] 2016-01-06 16:12
Yes please.







Sergiy Cherevko

Senior Programmer Analyst

DAC Group / Canada



416.492.3214 ext. 6295

**Comment by omarpando** [comment] 2016-01-06 23:30
@vtbassmatt 
Sure

**Closed** 2016-01-06 23:38 UTC
