### ISSUE TITLE
PowerShell activity fail when team project has a space in it

### ISSUE THREAD

**Issue by baywet** [Microsoft/vso-agent-tasks#364] opened 2015-08-05 12:17 UTC
Hi,
I'm not sure this is the right place to post that (uservoice?) so pardon me if it's not.
When the team project has a space in the name, all PowerShell activities (not azure, the stantard ones) fail.
Here is the error message we get.
'C:\agent\_work\9655a16e\<projectNameWithASpace>' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

We've tested the exact same settings on a project without space in the name and it works perfectly.

Note : the failing projects also have dashes in the name so maybe it's the dash and not the space causing the issue (" - ").

Thanks for your help!

**Comment by bryanmacfarlane** [comment] 2015-08-05 12:26
Thanks - we'll investigate

**Comment by ericsciple** [comment] 2015-10-23 04:17
Sorry for the absurd response time. I somehow missed this issue.

I'm not able to reproduce the issue. Can you confirm it's still an issue? Are you testing against RTM, RTM Update 1, or VSO? Any additional repro steps you can provide? I tried two things:
1) Project named with " - " in the middle, and used PowerShell Task pointing to a ps1 file nested in a folder that also had a " - " in the middle of the folder name.
2) Project named with " - " in the middle, and vsbuild task pointing to an SLN file nested in a folder that also had a " - " in the middle of the folder name.

Given the absurd response time - again sorry about that - this may be something has been fixed in the meantime. I'm testing against the sprint that just started rolling out today and will be rolled out to all the VSO instances within the next couple weeks.

Closing the issue for now. We can open it back up if it still repros.

**Closed by ericsciple** 2015-10-23 04:17 UTC

**Comment by baywet** [comment] 2015-10-27 01:00
Hi,
No problem, as project renaming as been released we renamed most of our projects (most of the projects were not following the naming conventions anyway).
We are using VSO online with build machines we installed (latest version of visual studio 2015, WS2012R2).
Here is the error message I get
Starting task: Powershell: $/ClientName - Project Name/BuildProcessTemplates/testscript.ps1

******************************************************************************

The directory name is invalid

******************************************************************************

Finishing task: PowerShell

**Comment by cristianomartins** [comment] 2016-10-17 14:37
I had same problem 


******************************************************************************
Starting task: Powershell: C:\Temp\ExecuteSQL.ps1
******************************************************************************
. 'C:\Temp\ExecuteSQL.ps1' -servername DBServer -databasename MyDatabse -filename C:\Temp\Script.sql -username ******** -password ********
Executing the following powershell script. (workingFolder = C:\Temp\ExecuteSQL.ps1)
C:\Temp\ExecuteSQL.ps1 -servername DBServer -databasename MyDatabse -filename C:\Temp\Script.sql -username ******** -password ********
The directory name is invalid
******************************************************************************
Finishing task: PowerShell
******************************************************************************
Task PowerShell failed. This caused the job to fail. Look at the logs for the task for more details.
Worker Worker-bb8159aa-4879-462f-b12c-8883197433d6 finished running job bb8159aa-4879-462f-b12c-8883197433d6
******************************************************************************
Finishing Build
******************************************************************************
