### ISSUE TITLE
Xamarin Test Cloud step does not stop after failure or success

### ISSUE THREAD

**Issue by sahino** [Microsoft/vso-agent-tasks#847] opened 2015-11-23 10:21 UTC
Hi,

Last week I have been playing with the Xamarin Test Cloud build step as part of the build pipe that I'm creating with a vso agent on an osx machine

For some reason, it seems that even if the UI test in the build succeeds or fails, the step does not finish  and stays in an endless loop with sending new invalid requests to test cloud. So the build actually never stops and i need to stop the build manually. 
When I trigger the exact same command (as shown in the console log) from the terminal, it starts, succeeds and finishes.

Any help would be really great.
Sahin 

Setup is as follows:

App File: ./PROJECT.iOS/bin/iPhone/$(Configuration)/PROJECTIOS.ipa
dSYM File (iOS only): (none)	
Team API Key: [REMOVED]
User Email	[REMOVED]
Devices	f85be48a
Series	master
Test Assembly Directory	./PROJECT.UITests/bin/$(Configuration)/
 
Advanced
Parallelization	None
System Language	English (United States)
test-cloud.exe Location	./packages/Xamarin.UITest.1.2.0/tools/test-cloud.exe

Optional Arguments	
Publish results to VSO/TFS	Checked	

And the console log seems like this.
---------------------------------------------
/BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].iOS/bin/iPhone/Debug/[PROJECT NAME REMOVED].ipa
##[Debug] 2015-11-20T13:57:54.388Z: dsym: 
##[Debug] 2015-11-20T13:57:54.388Z: teamApiKey: [TEAM API KEY REMOVED] 
##[Debug] 2015-11-20T13:57:54.388Z: user: [EMAIL REMOVED]
##[Debug] 2015-11-20T13:57:54.388Z: devices: [DEVICE ID REMOVED]
##[Debug] 2015-11-20T13:57:54.388Z: series: master
##[Debug] 2015-11-20T13:57:54.388Z: testDir: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug
##[Debug] 2015-11-20T13:57:54.388Z: parallelization: none
##[Debug] 2015-11-20T13:57:54.388Z: locale: en_US
##[Debug] 2015-11-20T13:57:54.389Z: testCloudLocation: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/packages/Xamarin.UITest*/tools/test-cloud.exe
##[Debug] 2015-11-20T13:57:54.389Z: optionalArgs: 
##[Debug] 2015-11-20T13:57:54.389Z: publishNUnitResults: true
##[Debug] 2015-11-20T13:57:54.389Z: 
##[Debug] 2015-11-20T13:57:54.390Z: cwd: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803
##[Debug] 2015-11-20T13:57:54.570Z: app=/BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].iOS/bin/iPhone/Debug/[PROJECT NAME REMOVED].ipa
##[Debug] 2015-11-20T13:57:54.571Z: dsym=
##[Debug] 2015-11-20T13:57:54.571Z: teamApiKey=[TEAM API KEY REMOVED] 
##[Debug] 2015-11-20T13:57:54.571Z: user=[EMAIL REMOVED]
##[Debug] 2015-11-20T13:57:54.571Z: devices=[DEVICE ID REMOVED]
##[Debug] 2015-11-20T13:57:54.572Z: series=master
##[Debug] 2015-11-20T13:57:54.572Z: testDir=/BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug
##[Debug] 2015-11-20T13:57:54.572Z: parallelization=none
##[Debug] 2015-11-20T13:57:54.573Z: locale=en_US
##[Debug] 2015-11-20T13:57:54.573Z: testCloudLocation=/BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/packages/Xamarin.UITest*/tools/test-cloud.exe
##[Debug] 2015-11-20T13:57:54.573Z: optionalArgs=
##[Debug] 2015-11-20T13:57:54.573Z: publishNUnitResults=true
##[Debug] 2015-11-20T13:57:54.573Z: app: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].iOS/bin/iPhone/Debug/[PROJECT NAME REMOVED].ipa
##[Debug] 2015-11-20T13:57:54.575Z: dsym: 
##[Debug] 2015-11-20T13:57:54.575Z: teamApiKey: [TEAM API KEY REMOVED] 
##[Debug] 2015-11-20T13:57:54.576Z: user: [EMAIL REMOVED]
##[Debug] 2015-11-20T13:57:54.576Z: devices: [DEVICE ID REMOVED]
##[Debug] 2015-11-20T13:57:54.576Z: series: master
##[Debug] 2015-11-20T13:57:54.576Z: testDir: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug
##[Debug] 2015-11-20T13:57:54.576Z: parallelization: none
##[Debug] 2015-11-20T13:57:54.576Z: locale: en_US
##[Debug] 2015-11-20T13:57:54.576Z: testCloudLocation: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/packages/Xamarin.UITest*/tools/test-cloud.exe
##[Debug] 2015-11-20T13:57:54.576Z: optionalArgs: 
##[Debug] 2015-11-20T13:57:54.577Z: Pattern found in testCloudLocation parameter
##[Debug] 2015-11-20T13:57:54.577Z: agent.buildDirectory=/BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803
##[Debug] 2015-11-20T13:57:54.835Z: find /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803
##[Debug] 2015-11-20T13:57:54.835Z: 2733 matches.
##[Debug] 2015-11-20T13:57:54.850Z: mono=/usr/local/bin/mono
##[Debug] 2015-11-20T13:57:54.850Z: build.buildId=197
##[Debug] 2015-11-20T13:57:54.851Z: Submitting to Xamarin Test Cloud: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].iOS/bin/iPhone/Debug/[PROJECT NAME REMOVED].ipa
2015-11-20T13:57:54.851Z: [command]/usr/local/bin/mono /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/packages/Xamarin.UITest.1.2.0/tools/test-cloud.exe submit /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].iOS/bin/iPhone/Debug/[PROJECT NAME REMOVED].ipa [TEAM API KEY REMOVED] --user [EMAIL REMOVED] --devices [DEVICE ID REMOVED] --series master --locale en_US --assembly-dir /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug --nunit-xml /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug/xamarintest_197.0.xml
2015-11-20T13:57:56.550Z: Negotiating file upload to Xamarin Test Cloud.
2015-11-20T13:57:57.655Z: Posting to https://testcloud.xamarin.com/ci/upload2
2015-11-20T13:57:57.655Z: 
2015-11-20T13:57:57.659Z: Uploading [PROJECT NAME REMOVED].UITests.dll ... Already uploaded.
2015-11-20T13:57:57.659Z: Uploading Xamarin.UITest.dll ... Already uploaded.
2015-11-20T13:57:57.659Z: Uploading nunit.framework.dll ... Already uploaded.
2015-11-20T13:57:57.678Z: 
2015-11-20T13:57:59.464Z: Uploading [PROJECT NAME REMOVED].ipa... 10%
2015-11-20T13:58:02.236Z: Uploading [PROJECT NAME REMOVED].ipa... 20%
2015-11-20T13:58:04.639Z: Uploading [PROJECT NAME REMOVED].ipa... 30%
2015-11-20T13:58:07.276Z: Uploading [PROJECT NAME REMOVED].ipa... 40%
2015-11-20T13:58:09.201Z: Uploading [PROJECT NAME REMOVED].ipa... 50%
2015-11-20T13:58:11.139Z: Uploading [PROJECT NAME REMOVED].ipa... 60%
2015-11-20T13:58:12.898Z: Uploading [PROJECT NAME REMOVED].ipa... 70%
2015-11-20T13:58:14.748Z: Uploading [PROJECT NAME REMOVED].ipa... 80%
2015-11-20T13:58:16.293Z: Uploading [PROJECT NAME REMOVED].ipa... 90%
2015-11-20T13:58:18.100Z: Uploading [PROJECT NAME REMOVED].ipa... 100%
2015-11-20T13:58:18.101Z: Uploading [PROJECT NAME REMOVED].ipa... 100%
2015-11-20T13:58:26.804Z: 
2015-11-20T13:58:26.804Z: Upload complete. Upload Id: d81fc15b-40c2-4337-a6d8-04770bc217bd
2015-11-20T13:58:26.804Z: 
2015-11-20T13:58:26.919Z: Status: Validating
2015-11-20T13:58:37.025Z: Status: Validating
2015-11-20T13:58:47.139Z: Status: Validating
2015-11-20T13:58:57.248Z: Status: Validating
2015-11-20T13:59:07.377Z: Status: Validating
2015-11-20T13:59:17.494Z: Status: Validating
2015-11-20T13:59:27.609Z: Status: Validating
2015-11-20T13:59:37.728Z: Status: Validating
2015-11-20T13:59:47.849Z: Status: Validating
2015-11-20T13:59:58.001Z: Status: Validating
2015-11-20T14:00:08.116Z: Status: Validating
2015-11-20T14:00:18.230Z: Status: Validating
2015-11-20T14:00:28.346Z: Status: Validating
2015-11-20T14:00:38.454Z: Status: Validating
2015-11-20T14:00:48.566Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:00:58.685Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:01:08.797Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:01:18.919Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:01:29.028Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:01:39.153Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:01:49.268Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:01:59.381Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:02:09.498Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:02:19.620Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:02:29.735Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:02:39.850Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:02:49.963Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:03:00.078Z: Status: Running on 1 device (0 / 1 completed)
2015-11-20T14:03:10.192Z: Status: Tests completed. Processing data.
2015-11-20T14:03:20.318Z: Status: Tests completed. Processing data.
2015-11-20T14:03:30.449Z: Downloading and merging NUnit xml reports.
2015-11-20T14:03:31.039Z: Saving report to: /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug/xamarintest_197.0.xml
2015-11-20T14:03:31.039Z: Status: Done
2015-11-20T14:03:31.039Z: 
2015-11-20T14:03:31.039Z: Total scenarios: 1
2015-11-20T14:03:31.039Z: Passed: 1
2015-11-20T14:03:31.039Z: Failed: 0
2015-11-20T14:03:31.039Z: Skipped: 0
2015-11-20T14:03:31.039Z: 
2015-11-20T14:03:31.040Z: Total steps: 1
2015-11-20T14:03:31.040Z: 
2015-11-20T14:03:31.040Z: Test report: https://testcloud.xamarin.com/test/[PROJECT NAME REMOVED].ios_d81fc15b-40c2-4337-a6d8-04770bc217bd/

So here it actually Succeeds and finishes...and then this find happens and from here it endlessly loops with error -> But it is shown as succesful tests in TFS report???

##[Debug] 2015-11-20T14:03:31.068Z: find /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug
##[Debug] 2015-11-20T14:03:31.068Z: 7 matches.
##[Debug] 2015-11-20T14:03:31.069Z: task result: Succeeded
##[Debug] 2015-11-20T14:03:31.069Z: Submitting to Xamarin Test Cloud: undefined
2015-11-20T14:03:31.069Z: [command]/usr/local/bin/mono /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/packages/Xamarin.UITest.1.2.0/tools/test-cloud.exe submit [TEAM API KEY REMOVED] --user [EMAIL REMOVED] --devices [DEVICE ID REMOVED] --series master --locale en_US --assembly-dir /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug --nunit-xml /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug/xamarintest_197.1.xml
2015-11-20T14:03:31.307Z: Usage:
2015-11-20T14:03:31.307Z:   test-cloud.exe submit <apk-ipa> <api-key> [options] [--include <nunit-category> | --category <nunit-category> | --exclude <nunit-category> | --fixture <nunit-fixture> | --data <file-or-directory>] ...
2015-11-20T14:03:31.307Z:   test-cloud.exe submit <apk-ipa> <api-key> keystore <storefile> <storepass> <keyalias> <keypass> [options] [--include <nunit-category> | --category <nunit-category> | --exclude <nunit-category> | --fixture <nunit-fixture> | --data <file-or-directory>] ...
2015-11-20T14:03:31.308Z: Run 'test-cloud.exe help submit' for more details.
##[Debug] 2015-11-20T14:03:31.323Z: Error executing test run: Error: /usr/local/bin/mono failed with return code: 2
##[Debug] 2015-11-20T14:03:31.323Z: find /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug
##[Debug] 2015-11-20T14:03:31.323Z: 7 matches.
##[Debug] 2015-11-20T14:03:31.324Z: task result: Failed
##[Debug] 2015-11-20T14:03:31.325Z: Submitting to Xamarin Test Cloud: undefined
2015-11-20T14:03:31.325Z: [command]/usr/local/bin/mono /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/packages/Xamarin.UITest.1.2.0/tools/test-cloud.exe submit [TEAM API KEY REMOVED] --user [EMAIL REMOVED] --devices [DEVICE ID REMOVED] --series master --locale en_US --assembly-dir /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug --nunit-xml /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug/xamarintest_197.2.xml
2015-11-20T14:03:31.539Z: Usage:
2015-11-20T14:03:31.539Z:   test-cloud.exe submit <apk-ipa> <api-key> [options] [--include <nunit-category> | --category <nunit-category> | --exclude <nunit-category> | --fixture <nunit-fixture> | --data <file-or-directory>] ...
2015-11-20T14:03:31.539Z:   test-cloud.exe submit <apk-ipa> <api-key> keystore <storefile> <storepass> <keyalias> <keypass> [options] [--include <nunit-category> | --category <nunit-category> | --exclude <nunit-category> | --fixture <nunit-fixture> | --data <file-or-directory>] ...
2015-11-20T14:03:31.540Z: Run 'test-cloud.exe help submit' for more details.
##[Debug] 2015-11-20T14:03:31.548Z: Error executing test run: Error: /usr/local/bin/mono failed with return code: 2
##[Debug] 2015-11-20T14:03:31.548Z: find /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug
##[Debug] 2015-11-20T14:03:31.548Z: 7 matches.
##[Debug] 2015-11-20T14:03:31.549Z: task result: Failed
##[Debug] 2015-11-20T14:03:31.549Z: Submitting to Xamarin Test Cloud: undefined
2015-11-20T14:03:31.549Z: [command]/usr/local/bin/mono /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/packages/Xamarin.UITest.1.2.0/tools/test-cloud.exe submit [TEAM API KEY REMOVED] --user [EMAIL REMOVED] --devices [DEVICE ID REMOVED] --series master --locale en_US --assembly-dir /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug --nunit-xml /BuildAgents/SahinAgent/_work/build/f6c1c35564778aef8c5c08087483e7be98fad6517fed91b4952874070dc76803/repo/[PROJECT NAME REMOVED].UITests/bin/Debug/xamarintest_197.3.xml
2015-11-20T14:03:31.755Z: Usage:
2015-11-20T14:03:31.756Z:   test-cloud.exe submit <apk-ipa> <api-key> [options] [--include <nunit-category> | --category <nunit-category> | --exclude <nunit-category> | --fixture <nunit-fixture> | --data <file-or-directory>] ...

...etcetera

**Comment by chrisrpatterson** [comment] 2015-11-23 12:46
Yang?

**Comment by yacaovsnc** [comment] 2015-11-23 15:49
We opened a pull request #796 on this issue.

**Comment by yacaovsnc** [comment] 2015-11-23 15:55
Pull request 796 is abandoned, but we will handle this situation from the infrastructure.

**Comment by sahino** [comment] 2015-11-24 08:45
Could you sort of explain what you mean with handling it from the infrastructure? Will it be automatically fixed from vso or do i need to pull and update the task myself?
And when will it be fixed?

Thanks in advance!

**Comment by sahino** [comment] 2015-11-26 07:50
Still have no answer on how the fix will be distributed.Can anyone answer this?

**Comment by yacaovsnc** [comment] 2015-11-30 14:44
@sahino 
The issue is tl.exit() doesn't stop the task execution (the attempted fix in the pull request was to make sure we stop task execution whenever we call tl.exit()).  We are going to fix the issue in the task-lib so that when we call tl.exit(), the task execution stops.  The fix won't be on this task itself, but on the depended task lib, that's what I meant by "fixed by infrastructure".

@chrisrpatterson would know more about how the fix will be distributed.

**Comment by bryanmacfarlane** [comment] 2015-11-30 14:50
I have a fix.  It will be pushed as an update to vso-task-lib which is pulled down when you install your agent.  So the fix will be to update your agent (single cmd line - see readme) when it's ready.  I'll reply back when it's checked in (today or tomorrow).

**Comment by sahino** [comment] 2015-12-01 12:27
@yacaovsnc , thanks for the clarification!
@bryanmacfarlane, good to hear that you managed to find a fix for this issue, very happy to hear that!

Could one of you ping me as soon as the fix is available?

Thanks in advance.
Sahin

**Comment by hankbeasley** [comment] 2016-01-31 21:29
I just setup new mac build agent. This is an issue.

**Comment by andremarques023** [comment] 2016-02-18 21:03
Same here. Can you guys inform us when the fix will be available?

**Comment by jamesmontemagno** [comment] 2016-03-01 05:01
I haven't seen this issue on Xamarin.Android projects, but perhaps iOS is different.

I don't wait for the results. You can pass an additional argument in of "--async" and it will upload and carry one.

**Comment by madhurig** [comment] 2016-03-25 14:11
Fix in the task is deployed to Visual Studio Team Services. Make sure to get the latest stable Mac agent as well.

**Closed by madhurig** 2016-03-25 14:11 UTC

**Comment by santosh47billion** [comment] 2017-09-05 12:45
I am facing this issue
Use regions/landmarks to skip ahead to chart.
0%
Long description.
0% of Tests passed.
Structure.
Chart type: pie chart.
pie with 1 slice.
Chart graphic.
0%
0/0Tests passed
Use regions/landmarks to skip ahead to chart.
0%
Long description.
0% of Devices passed.
Structure.
Chart type: pie chart.
pie with 1 slice.
Chart graphic.
0%
0/1Devices passed
Something went wrong while running your tests

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building run-test 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ run-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ run-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ run-test ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ run-test ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ run-test ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ run-test ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: target/run-test-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ run-test ---
[INFO] No tests to run.
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ run-test ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.931 s
[INFO] Finished at: 2017-09-05T09:22:48+02:00
[INFO] Final Memory: 16M/212M
[INFO] ------------------------------------------------------------------------
