### ISSUE TITLE
PS script failure 'AuthorizationManager check failed

### ISSUE THREAD

**Issue by asvyat** [Microsoft/vso-agent-tasks#974] opened 2015-12-12 00:33 UTC
Unable to run PS script on one of our machine, getting this error:
 Deployment failed on machine ...with following message : 'AuthorizationManager check failed.'

Checked and ExecutionPolicy is unrestricted

**Comment by ericsciple** [comment] 2015-12-21 16:10
Do you get this error when running an ad-hoc PowerShell script (PowerShell Script task) or when running one of the tasks implemented in PowerShell?

Note, PowerShell will still complain if the execution policy is set to unrestricted and you attempt to run a script that has a bad signing signature (e.g. downloaded a signed script and modified the contents - you would need to remove the signature also). Also it might be worth checking the execution policy of 64-bit PowerShell (C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe) and the 32-bit as well (C:\WINDOWS\SysWOW64\WindowsPowerShell\v1.0\powershell.exe).

**Comment by ericsciple** [comment] 2015-12-22 16:35
@asvyat also, is this for a build task or release management?

**Comment by asvyat** [comment] 2015-12-22 19:08
this was on release management

**Comment by ericsciple** [comment] 2015-12-23 15:49
@asvyat And which task? I think you missed one of my comments above.

**Comment by asvyat** [comment] 2015-12-23 18:49
task name: PowerShell on Target Machines
we try running PS script from the file share, checked and execution policy is Unrestricted in both 64 and 32 bit env.

**Comment by pryenugu** [comment] 2015-12-23 20:38
@asvyat, if you are running scripts from a a central share you might need to add the share to the trusted sites. Check this technet blog for solutions to this: http://blogs.technet.com/b/heyscriptingguy/archive/2012/10/29/how-to-run-powershell-scripts-from-a-shared-directory.aspx
Also, if some other group policies are into picture which are managed elsewhere this solution might not work and you would need to sign the scripts even though the Execution policy of the machine is set to Unrestricted.

**Comment by mvvsubbu** [comment] 2016-03-29 04:34
Closing the issue as the customer is unblocked with the work around.

**Closed by mvvsubbu** 2016-03-29 04:34 UTC
Labels: deployment

**Comment by tanyabr** [comment] 2016-07-20 06:43
I have the same error, tried everything listed above, but was unsuccessful... Could you try helping me resolve this?..
I use powerhsell on target machine task to run a deployment script from a shared location (release management). This is the error I receive:
2016-07-19T12:03:48.6324750Z 	 Deployment started on target machine...
2016-07-19T12:03:48.6324750Z System.AggregateException: Failed to execute the configuration data script. Consult the logs below for details of the error.
2016-07-19T12:03:48.6324750Z AuthorizationManager check failed. ---> System.Management.Automation.PSSecurityException: AuthorizationManager check failed. ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning message. Do you want to run \\versionserver\repo\RM\InitScripts\IISInitializationScript.ps1?
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
2016-07-19T12:03:48.6324750Z    at Microsoft.PowerShell.PSAuthorizationManager.RemoteFilePrompt(String path, PSHost host)
2016-07-19T12:03:48.6324750Z    at Microsoft.PowerShell.PSAuthorizationManager.CheckPolicy(ExternalScriptInfo script, PSHost host, Exception& reason)
2016-07-19T12:03:48.6324750Z    at Microsoft.PowerShell.PSAuthorizationManager.ShouldRun(CommandInfo commandInfo, CommandOrigin origin, PSHost host, Exception& reason)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.AuthorizationManager.ShouldRunInternal(CommandInfo commandInfo, CommandOrigin origin, PSHost host)
2016-07-19T12:03:48.6324750Z    --- End of inner exception stack trace ---
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2016-07-19T12:03:48.6324750Z    --- End of inner exception stack trace ---
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.ExecuteConfigurationData(IPowerShell powerShellSession, String dscConfiguration)
2016-07-19T12:03:48.6324750Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2016-07-19T12:03:48.6324750Z ---> (Inner Exception #0) System.Management.Automation.PSSecurityException: AuthorizationManager check failed. ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning message. Do you want to run \\versionserver\repo\RM\InitScripts\IISInitializationScript.ps1?
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
2016-07-19T12:03:48.6324750Z    at Microsoft.PowerShell.PSAuthorizationManager.RemoteFilePrompt(String path, PSHost host)
2016-07-19T12:03:48.6324750Z    at Microsoft.PowerShell.PSAuthorizationManager.CheckPolicy(ExternalScriptInfo script, PSHost host, Exception& reason)
2016-07-19T12:03:48.6324750Z    at Microsoft.PowerShell.PSAuthorizationManager.ShouldRun(CommandInfo commandInfo, CommandOrigin origin, PSHost host, Exception& reason)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.AuthorizationManager.ShouldRunInternal(CommandInfo commandInfo, CommandOrigin origin, PSHost host)
2016-07-19T12:03:48.6324750Z    --- End of inner exception stack trace ---
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-07-19T12:03:48.6324750Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-07-19T12:03:48.6481064Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-07-19T12:03:48.6481064Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-07-19T12:03:48.6481064Z    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-07-19T12:03:48.6481064Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2016-07-19T12:03:48.6481064Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2016-07-19T12:03:48.6481064Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2016-07-19T12:03:48.6481064Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2016-07-19T12:03:48.6481064Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)<---

**Comment by asvyat** [comment] 2016-07-20 15:01
The workaround is, have additional step before that to copy it locally to a temp folder, and run PS script local.

Sent from my Windows Phone
________________________________

**Comment by tanyabr** [comment] 2016-07-21 05:35
@asvyat Thanks for your reply!
I've tried running the script locally, it finishes successfully, but running the release again after it, still fails with the same error...  What am I missing here? I can't find the difference between machines that run the script successfully and that problematic one...

**Comment by asvyat** [comment] 2016-07-21 15:02
Make sure you update the release definition (master version), not the release instance of the executed one.
In another word, when you try to launch a release, click Edit and make sure that current definition has all your latest changes.

Sent from my Windows Phone
________________________________

**Comment by tanyabr** [comment] 2016-07-22 15:25
None of the changes I made were done on the release definition, the problem is in the machine configuration, so nothing actually changed in RM...
